

name:
  value: alibou

spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0



#eureka:
#  instance:
##    hostname: localhost
#    hostname: discovery-service
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 30
#  client:
#    service-url:
##      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://discovery-service:8761/eureka