
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: Zhb290798466
      host: localhost
      port: 27017
      database: notification
      authentication-mechanism: SCRAM-SHA-256


  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.alibou.notification.entity.OrderConfirmation, paymentConfirmation:com.alibou.notification.entity.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: alibou
    password: alibou
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8040

