server:
  port: 8050
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${DB_HOST:localhost}:3306/product
    url: jdbc:mysql://host.docker.internal:3306/product
    username: root
    password: Zhb290798466@

#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/product
#    username: alibou
#    password: alibou
  jpa:
    hibernate:
      ddl-auto: update
#    database: postgresql
#    database: mysql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    baseline-description: "init"
#    baseline-version: 0
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
