#spring:
#  config:
##    import: optional:configserver:http://localhost:8888
#    import: optional:configserver:http://config-server:8888 # for docker
#  application:
#    name: product-service

spring:
  application:
    name: product-service