    pipeline {
        agent any
        
        stages {
        stage('Checkout') {
        steps {
        // 检出代码库
    git branch: 'main', url: 'https://github.com/jiemazhb/commerce-website.git'
    }
    }

        stage('Build') {
        steps {
        // 编译项目
        sh './mvnw clean package -DskipTests'
    }
    }

        stage('Start Services') {
        steps {
        // 启动服务
        sh 'docker-compose up -d config-server discovery customer identity-service product gateway notification order payment'
        
        // 等待服务完全启动，添加一个延迟
    sleep time: 20, unit: 'SECONDS'
    }
    }

        stage('Run Tests') {
        steps {
        // 运行测试
        sh './mvnw test'
    }
    }

        stage('Deploy') {
        steps {
        // 根据需要定义部署步骤
        echo 'Deployment steps go here...'
    }
    }
    }

        post {
        always {
        // 任务结束后，停止并移除容器
        sh 'docker-compose down'
    }
        success {
        echo 'Pipeline completed successfully!'
    }
        failure {
        echo 'Pipeline failed.'
    }
    }
    }
