spring:
  cloud:
    config:
      enabled: false
#    import: optional:configserver:http://localhost:8888   # for local machine
#    import: optional:configserver:http://config-server:8888 # for docker
  application:
    name: discovery-service

eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #     defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 8761
